# Generated by Django 2.2.1 on 2019-05-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
